In [1]:
import sys
from pathlib import Path

# subir al directorio raíz del repo
sys.path.append(str(Path.cwd().parent))

from toolbox_ml.eda.core_describe_tipifica import describe_df, tipifica_variables
import pandas as pd

df = pd.read_csv("data/titanic.csv")  
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [2]:
display(describe_df(df))

,tipo,porcentaje_nulos,valores_unicos,porcentaje_cardinalidad
survived,int64,0.000000,2,0.224467
pclass,int64,0.000000,3,0.336700
sex,object,0.000000,2,0.224467
age,float64,19.865320,88,9.876543
sibsp,int64,0.000000,7,0.785634
parch,int64,0.000000,7,0.785634
fare,float64,0.000000,248,27.833895
embarked,object,0.224467,3,0.336700
class,object,0.000000,3,0.336700
who,object,0.000000,3,0.336700
adult_male,bool,0.000000,2,0.224467
deck,object,77.216611,7,0.785634
embark_town,object,0.224467,3,0.336700
alive,object,0.000000,2,0.224467
alone,bool,0.000000,2,0.224467

In [3]:
tipifica_variables(df, umbral_categorica=10, umbral_continua=0.5)

   Nombre variable      Tipo sugerido
0         survived            Binaria
1           pclass         Categorica
2              sex            Binaria
3              age  Numérica Discreta
4            sibsp         Categorica
5            parch         Categorica
6             fare  Numérica Discreta
7         embarked         Categorica
8            class         Categorica
9              who         Categorica
10      adult_male            Binaria
11            deck         Categorica
12     embark_town         Categorica
13           alive            Binaria
14           alone            Binaria